### ISSUE TITLE
SLIC instead of 2D segmentation

### ISSUE THREAD

**Issue by Stephanie-Shen324** [valeoai/SLidR#14]
Hi,

Would you mind sharing your thoughts on using SLIC to generate superpixel instead of a 2D image segmentor? I feel like the 2D segmentors are more mature than the SLIC algorithm and might have a more reasonable superpixel segments.

**Comment by CSautier** [comment]
Hi,
The purpose of the research was to have a fully unsupervised method. Most recent 2D image segmentor use supervised training on some external dataset, which would not have been compatible with our objective.

We still tried some off the shelf 2D unsupervised segmentor algorithms and they all had one of the 3 following issues : 
- They do not work well on some of the images in the nuScenes dataset (day and night, motion blur, and textureless images make the task very difficult)
- They are overconfident in the segmentation, resulting in only ~20 classes per image where the optimality for our method was around 150
- They segment per class and not per object (meaning 2 different cars will have the same segment) which might have benefits with a very low false positive rate, but damages the results a lot otherwise.
