### ISSUE TITLE
mIoU and fwIoU calculation

### ISSUE THREAD

**Issue by barzanisar** [valeoai/SLidR#36]
Hey, 

Why do you set IoU of classes with zero union to be 1 [here](https://github.com/valeoai/SLidR/blob/aecfb0229e250f25309a36ad409f0ea859e6cd6a/utils/metrics.py#L28)? 
 
Wouldn't that inflate mIoU values? Typically mIoU in other works is calculated by ignoring the IoU values with zero union i.e. ignore nan IoU values.

Also, where did you get the formula for calculating freq weighted IoU? 
I get different values if I use the formula:
freqweighted_iou = float(np.nansum(num_points_per_class * iou_per_class) / num_points_total) 

where nansum ignores the nan iou_per_class values resulting from zero union.

Thanks in advance for clarifying!

**Comment by CSautier** [comment]
Hi, thank you for your interest in our work.

If union is zero, it means that there is no element of this class in the ground truth, and we predicted zero element for this class. We should then get a perfect score for this class. However, as the score is computed on the entire validation set, I don't think this ever happens in practice.

As for the fwIoU, it's simply an intersection over union without caring about the classes, It's here computed as |A ∩ B| / (|A| + |B| - |A ∩ B|), with the slight simplification that |A| = |B|, as we have exactly one prediction and one GT for each non ignore points.

**Comment by barzanisar** [comment]
Hi, thanks for clarifying! Makes sense since the union for a full val set, for any class, will rarely be zero.

[In here](https://github.com/valeoai/SLidR/blob/aecfb0229e250f25309a36ad409f0ea859e6cd6a/utils/metrics.py#L24), you only set the row of the confusion matrix to 0 for ignored index. Is that right or am I misunderstanding? For an N by N confusion matrix, should we not set both row and col of the ignored index to zero? If we set only the row to zero, then fwIoU will take into account pts predicted to be in the ignored class.

**Comment by CSautier** [comment]
This is intended, as the 0 row of the confusion matrix correspond to GT ignore points which shouldn't influence the score. However the 0 column of the matrix correspond to points that have been predicted to be of class "0" which shouldn't be predicted, but those were points with actual GT that should count in the score. If I were to remove the 0 column, then a simple cheat would be to only predict 0 for all points and the system would get a perfect score. Another, maybe more usual way of doing that is to have a system that can't predict the ignore class.
In practice, at least for this work it doesn't matter at all, since the ignore class only appears negatively in the loss, and is then never predicted.
