### ISSUE TITLE
I wonder whether there is a bug around line [https://github.com/valeoai/SLidR/blob/main/pretrain/dataloader_nuscenes_spconv.py#L321](https://github.com/valeoai/SLidR/blob/main/pretrain/dataloader_nuscenes_spconv.py#L321 )?  (You should not comment this line) Because in your object detection code base, you use 4 features in object detection.

### ISSUE THREAD

**Issue by mu-cai** [valeoai/SLidR#5]
I wonder whether there is a bug around line [https://github.com/valeoai/SLidR/blob/main/pretrain/dataloader_nuscenes_spconv.py#L321](https://github.com/valeoai/SLidR/blob/main/pretrain/dataloader_nuscenes_spconv.py#L321 )?  (You should not comment this line) Because in your object detection code base, you use 4 features in object detection.

_Originally posted by @mu-cai in https://github.com/valeoai/SLidR/issues/3#issuecomment-1197528693_

**Comment by CSautier** [comment]
You are right there was indeed an issue, as this was not consistent with the pre-training for the results I reported.
I couldn't reproduce a working environment with spconv 1.2, so I created a new branch with spconv 2.x support, if you do use spconv 1.2, please tell me if the code runs normally. Otherwise I will soon reproduce object detection results with spconv 2.x but I cannot guarantee that this will not affect results.

**Comment by mu-cai** [comment]
Thank you for your information! Wait for your results

**Comment by CSautier** [comment]
The results were slightly below the ones I got with spconv 1.2, but probably within range of the standard deviation for object detection, thus I'm considering that we can use either version.
